language: python
python:
  - "2.7"

env:
  - CFLAGS="-O0"

before_install:
  - sudo apt-get install -qq libxml2-dev libxslt-dev

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# virtualenv:
#    system_site_packages: true

# database creation
before_script:
  - psql -c 'create database preciosa;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d preciosa
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d preciosa
  - python manage.py migrate cities_light

# command to run tests
script: python manage.py test
